#!/bin/bash
#-- The Descriptor Script that prints the description of all my scripts
CYAN='\033[0;36m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' 
RED='\033[0;37m'

printf "$CYAN\nSCRIPTS_PATH:$YELLOW .\n\n"

for i in `ls -p ./ | grep -v / ` 
do
	printf "$NC${i^^}$YELLOW - $GREEN$i\n"
	DESC=`cat ./$i| grep -E '^#--.*'`
	printf "$CYAN$DESC\n"
	printf "\n\n"
done

